[package]
name = "cloth-sim"
version = "0.1.0"
authors = ["Iman Hosseini <hosseini.iman@yahoo.com>"]

[dependencies]
gl = "0.10.0"

[dependencies.sdl2]
version = "0.31.0"
features = ["bundled", "static-link"]